# Generated by Django 5.0.6 on 2024-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.PositiveIntegerField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
